name: Deploy to Replit

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Replit CLI
      run: npm install -g replit-cli
    - name: Replit Login
      run: replit login --token ${{ secrets.REPLIT_TOKEN }}
    - name: Push to Replit
      run: replit push -r yourusername/your-repo-name
